services:
  stats-server:
    build: stats/stats-server
    image: stats/stats-server
    container_name: events-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.3
    container_name: events-stats-server-db
    ports:
      - "54320:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  events-service:
    build: main-service
    image: main-service
    container_name: events-main-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - events-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://events-db:5432/events
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS-SERVER_URL=http://stats-server:9090

  events-db:
    image: postgres:16.3
    container_name: events-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=events
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10